stages:
  - test
  - build

test:
  image: node:12.6.0
  stage: test
  before_script:
    - npm install
  script:
    - npm test
deploy:
    image: node:12.6.0
    before_script:
    - apt-get -qq update
    - npm set progress=false
    - npm install --silent
    script:
    - npm run build
    - apt-get install -yqq ruby ruby-dev --silent
    - gem install dpl
    - dpl --provider=heroku --app=toshiuk-infomaps --api-key=$HEROKU_PRODUCTION_API_KEY
    only:
    - master